name: Check Hermes

on:
  schedule:
    - cron: "*/5 * * * *"  # 毎5分ごとに実行
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python check_hermes.py
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
